[package]
name = "liturgy-for-the-mushroom-at-the-end-of-the-world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
nannou = "0.18.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
